"""add work_report_documents table

Revision ID: 1f9cfc8c0fe9
Revises: 0010
Create Date: 2026-08-21 09:37:41.131649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f9cfc8c0fe9'
down_revision: Union[str, Sequence[str], None] = '0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_report_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('pages_with_table', sa.Integer(), nullable=False),
    sa.Column('pages_without_table', sa.Integer(), nullable=False),
    sa.Column('entries_created', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: autogenerate가 work_report_entries의 기존 인덱스(ix_work_report_entries_department,
    # ix_work_report_entries_period) 삭제도 같이 잡아냈는데, 이번 작업(work_report_documents
    # 테이블 추가)과 무관한 모델-마이그레이션 드리프트라 여기서는 건드리지 않는다.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_report_documents')
    # ### end Alembic commands ###
